name: App with Github Actions, ArgoCD

on:
  workflow_dispatch
  # push:
  #  branches:
  #   - main
  #  paths-ignore:
  #    - 'manifest/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Make application.properties
      run: |
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES }}" > ./application.properties
      shell: bash

    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml
      
    - name: Naming jar file
      run: mv ./target/*.jar ./target/app.jar

    - name: Check jar file
      run: ls ./target

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./target/*.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - uses: actions/checkout@v4
      with:
        repository: renesuno/eks-ecr-argocd
        ref: main
        token: ${{ secrets.TOKEN }}
    
    - name: Set up Image
      run: |
        sed -i "s%image: ${{ secrets.DOCKERHUB_USERNAME }}/eks-ecr-argocd:[A-z0-9]*%image: ${{ secrets.DOCKERHUB_USERNAME }}/eks-ecr-argocd:${{ github.sha }}%" ./manifest/argocd-app.yaml

    - name: Commit and push changes
      run: |
        git config --local user.email "renesuno@gmail.com"
        git config --local user.name "renesuno"
        git add .
        git commit -m "Update application image version for ArgoCD"
        git push
